# Generated by Django 6.1.1 on 2026-09-21 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GCCDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UAE', 'United Arab Emirates'), ('KSA', 'Saudi Arabia'), ('Qatar', 'Qatar'), ('Oman', 'Oman'), ('Bahrain', 'Bahrain'), ('Kuwait', 'Kuwait')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('year_of_migration', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcc_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
