# Generated by Django 6.1.1 on 2026-09-21 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=150)),
                ('ward_number', models.CharField(max_length=20)),
                ('family_location', models.CharField(choices=[('Home Country', 'Home Country'), ('With Member in GCC', 'With Member in GCC')], max_length=30)),
                ('emergency_contact_name', models.CharField(max_length=150)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('norka_id_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Need Help', 'Need Help')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
