# Generated by Django 6.1.1 on 2026-09-21 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_homedetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsAndJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_qualification', models.TextField()),
                ('professional_skills', models.TextField()),
                ('looking_for_job', models.BooleanField(default=False)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills_and_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
